name: Terraform Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environnement cible"
        required: true
        default: "dev"
        type: choice
        options: [dev, staging, prod]

env:
  TF_VERSION: "1.5.0"
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
          TF_VAR_alert_email: ${{ secrets.TF_VAR_alert_email }}

      - name: Select Workspace
        run: |
          terraform workspace select ${{ github.event.inputs.environment || 'dev' }} \
          || terraform workspace new ${{ github.event.inputs.environment || 'dev' }}

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="environment=${{ github.event.inputs.environment || 'dev' }}" \
            -out=tfplan \
            -no-color
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
          TF_VAR_alert_email: ${{ secrets.TF_VAR_alert_email }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Output ALB DNS
        run: terraform output alb_dns_name
